// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-Lkq6VHIGRxZOb8nnNaGDrUcOfli_H1I',
    appId: '1:245769007460:web:ee00602879d03b955a8a71',
    messagingSenderId: '245769007460',
    projectId: 'cutimate-97bd4',
    authDomain: 'cutimate-97bd4.firebaseapp.com',
    storageBucket: 'cutimate-97bd4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYO1XS6X8q03tKsnivlELoguAvr3lwQ9M',
    appId: '1:245769007460:android:31ae7a16292e9c325a8a71',
    messagingSenderId: '245769007460',
    projectId: 'cutimate-97bd4',
    storageBucket: 'cutimate-97bd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7DIJm8kMQ1qtKHj1QNIq-5BLsIVTZVnE',
    appId: '1:245769007460:ios:d59f667f91535c2e5a8a71',
    messagingSenderId: '245769007460',
    projectId: 'cutimate-97bd4',
    storageBucket: 'cutimate-97bd4.firebasestorage.app',
    iosClientId:
        '245769007460-9188nijupv9hm7c0v2bb8e1kf1l22cfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.cutimateapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7DIJm8kMQ1qtKHj1QNIq-5BLsIVTZVnE',
    appId: '1:245769007460:ios:d59f667f91535c2e5a8a71',
    messagingSenderId: '245769007460',
    projectId: 'cutimate-97bd4',
    storageBucket: 'cutimate-97bd4.firebasestorage.app',
    iosClientId:
        '245769007460-9188nijupv9hm7c0v2bb8e1kf1l22cfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.cutimateapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-Lkq6VHIGRxZOb8nnNaGDrUcOfli_H1I',
    appId: '1:245769007460:web:4875f96386944dce5a8a71',
    messagingSenderId: '245769007460',
    projectId: 'cutimate-97bd4',
    authDomain: 'cutimate-97bd4.firebaseapp.com',
    storageBucket: 'cutimate-97bd4.firebasestorage.app',
  );
}
